name: Build 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  

    - name: Compile Code and Package Artifact
      working-directory: ./myapp
      run: mvn clean package

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: myapp-jar-${{ env.newVersion }}
        path: ${{ env.JAR_PATH }}