name: Build 

on:
  push:
    # TODO: Remove 'pipeline-setup' branch trigger before merging to master.
    branches:
      - master
      - pipeline-setup

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update project version
      working-directory: ./myapp
      run: |
        version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        newVersion=$(echo $version | awk -F'[.-]' '{if (NF == 3) print $1"."$2"."$3+1; else print $1"."$2"."$3+1"-"$4}')
        echo "newVersion=$newVersion" >> "$GITHUB_ENV"
        mvn versions:set -DnewVersion=$newVersion
        echo "Updated version: $newVersion"

    - name: Compile Code and Package Artifact
      working-directory: ./myapp
      run: mvn clean package
  
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: myapp-jar-${{ env.newVersion }}
        path: ./myapp/target/myapp-*
  
  build_and_publish_docker:
    runs-on: ubuntu-latest
    needs: build # Make sure this stage runs after the build stage
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/myapp:${{ env.newVersion }}



